language: generic
sudo: required
dist: trusty
before_install:
    - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
    - chmod 755 ./travis-tool.sh
    - wget -nv https://apt.puppetlabs.com/puppetlabs-release-pc1-trusty.deb
    - sudo dpkg -i puppetlabs-release-pc1-trusty.deb
    - sudo rm -f puppetlabs-release-pc1-trusty.deb
    - sudo apt-get update -qq
    - sudo apt-get install -qq puppet-agent -y
    - sudo apt-get install -qq git -y
    - sudo /opt/puppetlabs/puppet/bin/gem install r10k
    - git clone https://github.com/datashield/datashield-infrastructure.git /tmp/datashield-infrastructure
    - sudo gem install r10k
    - ls /opt/puppetlabs/puppet/bin/
    - sudo find / -name r10k
    - cd /tmp/datashield-infrastructure/puppet/environments/datashield_travis && sudo /home/travis/.rvm/gems/ruby-2.3.1/gems/r10k-2.4.3/bin/r10k puppetfile install && cd -
    - sudo /opt/puppetlabs/bin/puppet apply /tmp/datashield-infrastructure/puppet/environments/datashield_travis/manifests/site.pp --environment datashield_travis --environmentpath /tmp/datashield-infrastructure/puppet/environments

script:
    - sudo ./travis-tool.sh install_github jimhester/covr
    - ./travis-tool.sh run_tests

after_failure:
    - sudo ./travis-tool.sh dump_logs
    - sudo cat /var/log/opal/stdout.log

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
    - Rscript -e 'covr::codecov()'

